### ISSUE TITLE
Run Instruction

### ISSUE THREAD

**Issue by badlyans** [tomerv/csr2midi#2]
Hi tomerv,  Thank you for making this available and posting on the link on CASIO forum.  I downloaded anaconda and pip installed mido.  As I am not a programmer, I am wondering if you would be so kind as to add some instructions on how to use the run the code? I can click the play button and I get this back

runfile('C:/Users/Dennis Badlyans/Desktop/csr2midi-main/csr2midi.py', wdir='C:/Users/Dennis Badlyans/Desktop/csr2midi-main')
usage: csr2midi.py [-h] [-v] csr_file
csr2midi.py: error: the following arguments are required: csr_file

I tried adding in the csr_file name as a string to the end of the command, I tried it with csr_file='filename' as a part of runfile, i tried not as a string and got nowhere.  Can you help?

**Comment by tomerv** [comment]
Hi @badlyans , if you are using Windows I can suggest one of these options:

Option 1:
In File Explorer, drag the CSR file to csr2midi.py. If all works well, you will see a MIDI file created there.

Option 2:
1. In File Explorer, open the directory with csr2midi.py.
2. Hold the Shift key and right click anywhere in the directory (but not on any specific file, and make sure that no file is selected).
3. Choose "Open PowerShell window here".
4. In the PowerShell window, type "python csr2midi.py filename.csr" - but replace filename with the name of your file.

Let me know if this work.

I'll think how to package this in a way that is more accessible to everyday users.

**Comment by badlyans** [comment]
Hi @tomerv .  Thank you for the quick reply - Option 2 worked with your test files.
 
Option 1 doesn't seem to work - can't drag a file onto another file in windows 10.
Option 2 didn't work without installing python from Microsoft store and installing mido (even though I have anaconda and had the PATH settings done in that process).  

After doing that, I got an error message that seems to indicate something is wrong with my file:
"codec can't decode byte 0xff in position 5: invalid start byte"

Tried on test files and it works well - I just realized that even though your post was on PX-160 question in the Casio forum, the README files specifies that it only supports PX-130 only.  Thanks again.  Guess I might need to get cables to record for now.

**Comment by tomerv** [comment]
Do you mind uploading an example file from your piano model? If it is
similar to my model, I can probably support it.

Since this is a public website, make sure to not upload anything you want
to keep private.

**Comment by badlyans** [comment]
That would be great!  Here are two samples.
[PX-160.zip](https://github.com/tomerv/csr2midi/files/5867702/PX-160.zip)

**Comment by tomerv** [comment]
I made some changes, please check if it works well now.

By the way, I recommend buying a cable anyway, they're pretty cheap on AliExpress.

**Comment by badlyans** [comment]
It works!  Thank you so much for your help.
I'll check out AliExpress for the cables - Do you have specific ones you like?

**Comment by tomerv** [comment]
I bought these MIDI USB cables:
* For iPhone: https://a.aliexpress.com/_BTraJx
* For Android with USB type C: https://a.aliexpress.com/_B1uWf3

**Comment by badlyans** [comment]
Perfect!  thanks again!

**Comment by badlyans** [comment]
I just realized, this cable is for the USB port - do you use this cable to record your audio directly or is it used to transfer the files?
I have a cable that connects to my laptop but I can only transfer the CSR file.  I was thinking of getting a cable to just directly record the music onto my PC... was thinking of getting the dual audio jack to USB.

**Comment by tomerv** [comment]
I believe your piano has a MIDI-over-USB interface (my model does), but you
should check the manual. If it does, then you can connect it to the
computer and use some software that knows how to work with MIDI. It records
the key presses, not the audio.

If you want to record audio you will need an audio cable. They are also
inexpensive, but probably better to buy locally.

**Comment by badlyans** [comment]
Looks like mine has the same feature - I downloaded multitrackstudio lite edition and was able to record directly.  This is much easier than recording one piece at a time and transferring it over.  Thanks again for all your help and guidance!
