### ISSUE TITLE
Px 330

### ISSUE THREAD

**Issue by Robsia** [tomerv/csr2midi#3]
Hi. Is there any way you could make this work on music created on a PX 330? Thanks 😊

**Comment by tomerv** [comment]
I can certainly try!
I would need from you an example file from the PX-330 that I can analyze. It should be a file that uses all the features that you need support for, and of course it should be something that you don't mind sharing.

**Comment by Robsia** [comment]
It's ok. I'm an idiot and hadn't realised you can actually save as either a csr or a midi file from the px 330. Thanks anyway.
