### ISSUE TITLE
Compatibility for px770

### ISSUE THREAD

**Issue by EJoftheVern** [tomerv/csr2midi#5]
Raising issue for added support of px770. I'm able to provide files for testing

**Comment by tomerv** [comment]
Sure, I can try to add it. Please provide a few example files, and please be aware that they will be public once you post them here.

**Comment by EJoftheVern** [comment]
Hi,

Thankyou for taking a look into this.

I've attached 3 sample files. C Major scale with some chords afterwards, Just playing every note on the keyboard and then a really really bad attempt at playing some Satie (injured my finger yesterday so kept hitting the wrong notes). Let me know if you need any further details.

[Px-770 samples.zip](https://github.com/tomerv/csr2midi/files/7960313/Px-770.samples.zip)

**Comment by tomerv** [comment]
Hi @EJoftheVern ,
Thanks for attaching the files. I started looking into it.
Right now, I see 2 major issues:
* The PX-770 supports key release velocity, which csr2midi currently doesn't understand correctly. Should be an easy fix, but to make sure I do it correctly, can you please upload another file, where you test a few different release velocities? Say from fastest to slowest. Just a few is enough, I mainly want to know the range and which values (in the file) correspond to which velocities.
* I think I'm interpreting sustain pedal information incorrectly. Did you use the pedal in the files you attached? Please add a new file with a simple note sequence (like C major scale) with and without the pedal. Some examples of the other pedals will be helpful as well, but I'll need you to tell me exactly which pedals you pressed and in what order.

Other than that, I think there is also some less important information in the file, but let's leave that for later.

**Comment by EJoftheVern** [comment]
Thanks ever so much for getting back to me. Unfortunately the usb connection on the piano seems to be having some issues that I’m going to need to diagnose. I can record fine but when I plug my laptop in to copy the files over, although it can see the piano as a storage device, it cannot open it. I’ll close the request for now and get back to you if I do ever manage to get it working again. Think I might need to try ordering a replacement cable as a start as this one’s a bit dodgy!!
