### ISSUE TITLE
Support for Casio AP-250

### ISSUE THREAD

**Issue by AkshayKumar41** [tomerv/csr2midi#6]
Requesting support for Casio AP 250
While attempting to do it myself, I noticed that "BC" = middle c instead of 4c. Other than that, I didn't notice anything different. The issue right now is that I am getting the raw note but I cannot seem to get any dynamics or pedal. I am only using the sustain pedal. Chords and normal notes work fine. Let me know what file sequences (the notes, amount of pressing, pedals, chords, all notes, songs, etc.) and I will send the CSR files. Thanks!

**Comment by tomerv** [comment]
Hi @AkshayKumar41 ,
Please send CSR files of the following sequences:
1. Press & depress each white key, from the lowest to highest, one by one.
2. Hold the sustain pedal and make a few notes (e.g. do-re-mi), then release the pedal. Do that a few times.
3. Press middle C a few times, from the softest possible to the maximum force with slowly increasing dynamics.
I'll see what I can do with that.

**Comment by AkshayKumar41** [comment]
[CSR2MIDI.zip](https://github.com/tomerv/csr2midi/files/8459460/CSR2MIDI.zip)
I've attached the 3 files. For the sustain pedal trial, I played a C Major where I pressed the pedal, went up, released the pedal, and the same for going down.

**Comment by AkshayKumar41** [comment]
I forgot to mention that the AP-250 piano contains a "Brilliance" and "Touch Response" buttons. Touch Response makes it easier to play louder, meaning that a lighter tap registers with more noise. Brilliance allows it to sound more separated. I'm not sure how to describe it, but it makes it less "mushy". I normally use both of these, but if it is unable to be supported it is fine.

**Comment by AkshayKumar41** [comment]
Learned to directly record instead. Will close the issue.
